### ISSUE TITLE
Eslint failing

### ISSUE THREAD

**Issue by kball** [akxcv/vuera#51]
I checked out the code to try to work on https://github.com/akxcv/vuera/issues/50 and in my first checkin found eslint failing.

When I stash my changes and go back to master, it is still failing, so I think it probably has to do with a version change in eslint rather than the code I'm introducing.

The issue I see is:

```
kball-2:vuera kball$ npm run lint

> vuera@0.2.2 lint /Users/kball/git/vuera
> eslint .

ImportDeclaration should appear when the mode is ES6 and in the module context.
AssertionError [ERR_ASSERTION]: ImportDeclaration should appear when the mode is ES6 and in the module context.
    at Referencer.ImportDeclaration (/Users/kball/git/vuera/node_modules/escope/lib/referencer.js:591:34)
    at Referencer.Visitor.visit (/Users/kball/git/vuera/node_modules/esrecurse/esrecurse.js:104:34)
    at Referencer.Visitor.visitChildren (/Users/kball/git/vuera/node_modules/esrecurse/esrecurse.js:83:38)
    at Referencer.Program (/Users/kball/git/vuera/node_modules/escope/lib/referencer.js:419:18)
    at Referencer.Visitor.visit (/Users/kball/git/vuera/node_modules/esrecurse/esrecurse.js:104:34)
    at Object.analyze (/Users/kball/git/vuera/node_modules/escope/lib/index.js:153:16)
    at EventEmitter.module.exports.api.verify (/Users/kball/git/vuera/node_modules/eslint/lib/eslint.js:892:35)
    at localVerify (/Users/kball/git/vuera/node_modules/eslint-plugin-html/src/index.js:107:14)
    at EventEmitter.eslint.verify (/Users/kball/git/vuera/node_modules/eslint-plugin-html/src/index.js:147:18)
    at processText (/Users/kball/git/vuera/node_modules/eslint/lib/cli-engine.js:264:31)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuera@0.2.2 lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuera@0.2.2 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kball/.npm/_logs/2018-07-30T22_08_57_613Z-debug.log
```

According to this eslint issue: https://github.com/eslint/eslint/issues/10349 updating eslint is likely to resolve it.

**Comment by akxcv** [comment]
Hi! For some reason, I cannot reproduce this problem. Have you tried running `yarn lint`?
